name: Ponicode DogString
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - main
      - UpdateML
  pull_request:
    branches:
      - master
      - main
      - UpdateML
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildâ€
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get paths
        run: |
          git show --pretty="" --name-only ${{ github.sha }} > PATHS_TO_CHANGED_FILES.txt
      - uses: ponicode/dogstring-action@master
        with:
          repo_path: ./
          auth_token: ${{ secrets.PONICODE_TOKEN }}
          all_repo: True
        # Creates pull request with all changes in file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3